#!/usr/bin/env python

import lxml.etree as ET
from bottle import route, run, template, static_file, response
import cubes

import json

workspace = cubes.Workspace()
workspace.register_default_store("sql", url="sqlite:///data.sqlite")
workspace.import_model("./cubes/model.json")

browser = workspace.browser("activities")

xslt = ET.parse('tcx_to_csv.xsl')
transform = ET.XSLT(xslt)

device_xslt = ET.parse('tcx_to_device.xsl')
device_transform = ET.XSLT(device_xslt)

@route('/bower_components/<path:path>')
def bower_components(path):
  return static_file(path, root='./bower_components')

@route('/activities/<path:path>')
def activities_tcx(path):
  dom = ET.parse('./activities/%s' %(path))
  response.content_type = 'text/text'
  return str(transform(dom))
  
@route('/device/<path:path>')
def device_tcx(path):
  dom = ET.parse('./activities/%s' %(path))
  response.content_type = 'text/text'
  return str(device_transform(dom))

@route('/index.html')
def index():
  return static_file('index.html', root='.')

@route('/index.js')
def index_js():
  return static_file('index.js', root='.')

@route('/utils.js')
def tcx_parser():
  return static_file('utils.js', root='.')
  
@route('/tcx_to_csv.xsl')
def tcx_to_csv():
  return static_file('tcx_to_csv.xsl', root='.')

@route('/activities.csv')
def activities():
  return static_file('activities/Activities.txt', root='.')

@route('/all-points-group')
def all_points_group():
  res = browser.aggregate()
  return json.dumps(res.summary)

run(host='localhost', port=8000)


